#! /bin/bash
###########################################################################
#               i3wm main configuration file
#                   Author: Jayce Cao
#                   Date: 13, May 2017
###########################################################################

set $mod Mod4

###########################################################################
#                       autostart program
# Tray icons
exec --no-startup-id nm-applet
# Power managment
exec --no-startup-id meta-power-manager
###########################################################################
# Windows title and applications font
font pango:DejaVuSans 12


# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# Shortcuts for starting programs quickly
bindsym $mod+Return exec urxvt
bindsym $mod+c exec google-chrome-stable
bindsym $mod+v exec vim
bindsym --release $mod+Print exec scrot -s

# open a new window without a window border
new_window 1pixel

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+t split h

# split in vertical orientation
bindsym $mod+g split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1: VIM
bindsym $mod+2 workspace 2: XTerm
bindsym $mod+3 workspace 3: Chrome
bindsym $mod+4 workspace 4: NetEase-Music
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2: XTerm
bindsym $mod+Shift+3 move container to workspace 3: Chrome
bindsym $mod+Shift+4 move container to workspace 4: NetEase-Music
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"


###########################################################################################################
#                                   Power Managment
# Use i3lock to lock screen. The background color of lock screen is #111111
set $Locker i3lock -c "#111111" && sleep 1
set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Shift+s) shutdown
mode "$mode_system" {
    bindsym l exec --no-startup-id $Locker, mode "default"
    bindsym e exec --no-startup-id i3-msg exit, mode "default"
    bindsym s exec --no-startup-id $Locker && systemctl suspend, mode "default"
    bindsym h exec --no-startup-id $Locker && systemctl hibernate, mode "default"
    bindsym r exec --no-startup-id systemctl reboot, mode "default"
    bindsym Shift+s exec --no-startup-id systemctl poweroff -i, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+Pause mode "$mode_system"
############################################################################################################

############################################################################################################
#                                   Volume and Brightness Managment
bindsym XF86AudioRaiseVolume exec --no-startup-id amixer -q set Master 2dB+ unmute
bindsym XF86AudioLowerVolume exec --no-startup-id amixer -q set Master 2dB- unmute
bindsym XF86AudioMute exec --no-startup-id amixer -q set Master toggle
bindsym XF86MonBrightnessDown exec --no-startup-id ~/.brightness_down.sh
bindsym XF86MonBrightnessUp exec --no-startup-id ~/.brightness_up.sh
############################################################################################################

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        # The i3bar is on top
        position top
        font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
        status_command i3blocks -c ~/.config/i3/i3blocks.conf
        # Set the transparent i3bar
        i3bar_command i3bar -t

        colors {
            # Set the background color of i3bar
            background #10101000
            # Set the color of i3bar's text
            statusline #000000FF
        }
}
